/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peminjamanonline_sister_kelompok4;

import com.mycompany.peminjamanonline_sister_kelompok4.KafkaProducer.KafkaPengajuanProducer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

/**
 *
 * @author ACER
 */
public class PengajuanPinjaman extends javax.swing.JFrame {

    private final int iduser; // Store the user ID

    public void KirimData(String iduser, String jumlah, String tenor, String sukuBunga,
            String angsuranBulanan, String tanggalCair, String totalCair,
            String sisaTagihan, String status, String status_pengajuan) {
        
        
        Properties props = new Properties();
        props.setProperty("bootstrap.servers", "localhost:9092");
        props.setProperty("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.setProperty("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

        try (KafkaProducer<String, String> producer = new KafkaProducer<>(props)) {
            String message = String.format(
                    "iduser=%s, jumlah=%s, tenor=%s, suku_bunga=%s, angsuran_bulanan=%s, tanggal_cair=%s, total_cair=%s, sisa_tagihan=%s, status=%s, status_pengajuan=%s",
                    iduser.trim(),
                    jumlah.trim(),
                    tenor.trim(),
                    sukuBunga.trim(),
                    angsuranBulanan.trim(),
                    tanggalCair.trim(),
                    totalCair.trim(),
                    sisaTagihan.trim(),
                    status.trim(),
                    status_pengajuan.trim()
            );
            ProducerRecord<String, String> record = new ProducerRecord<>("pengajuan-pinjaman", message);

            producer.send(record, (metadata, exception) -> {
                if (exception != null) {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this,
                                "Error mengirim data ke Kafka: " + exception.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    });
                    exception.printStackTrace();
                } else {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this,
                                "Pengajuan berhasil!",
                                "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    });
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Creates new form PengajuanPinjaman
     *
     * @param userId
     */
    public PengajuanPinjaman(int userId) {
        this.iduser = userId;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAjukan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        CbTenor = new javax.swing.JComboBox<>();
        txtBunga = new javax.swing.JLabel();
        txtCicilan = new javax.swing.JLabel();
        btnTampil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengajuan Pinjaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(7, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jumlah :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tenor :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Bunga :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Cicilan :");

        btnAjukan.setBackground(new java.awt.Color(102, 102, 255));
        btnAjukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAjukan.setForeground(new java.awt.Color(255, 255, 255));
        btnAjukan.setText("Ajukan");
        btnAjukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjukanActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(102, 102, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        CbTenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1 Bulan", "3 Bulan", "6 Bulan", "12 Bulan", " "}));
        CbTenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTenorActionPerformed(evt);
            }
        });

        txtBunga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBunga.setText("1 %");

        txtCicilan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCicilan.setText("Isi");

        btnTampil.setBackground(new java.awt.Color(102, 102, 255));
        btnTampil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampil.setForeground(new java.awt.Color(255, 255, 255));
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CbTenor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnKembali)
                                                .addGap(68, 68, 68)
                                                .addComponent(btnAjukan))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtBunga))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtCicilan)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(btnTampil)))))))
                                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(CbTenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtBunga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtCicilan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAjukan)
                                        .addComponent(btnKembali))
                                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>                        

    private void CbTenorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }


    private void btnAjukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjukanActionPerformed
        try {
            // Hapus format Rp dan koma dari input jumlah
            int jumlahPinjaman = Integer.parseInt(txtJumlah.getText().replaceAll("[^\\d]", ""));

            int batasMaksPinjaman = 20000000;
            int batasMinimuPinjaman = 1000000;

            // Validasi jumlah pinjaman
            if (jumlahPinjaman < batasMinimuPinjaman) {
                JOptionPane.showMessageDialog(this, "Jumlah pinjaman minimal Rp 1.000.000.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (jumlahPinjaman > batasMaksPinjaman) {
                JOptionPane.showMessageDialog(this, "Jumlah pinjaman tidak boleh lebih dari Rp 20.000.000.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String tenor = CbTenor.getSelectedItem().toString();
            int tenorBulan = Integer.parseInt(tenor.split(" ")[0]); // Misalkan formatnya "12 Bulan"

            double bunga = 0.01; // Default 1%
            txtBunga.setText("1"); // Set text field

            // Hitung tanggal pengajuan dan tanggal cair
            LocalDate tanggalPengajuan = LocalDate.now();
            LocalDate tanggalCair = tanggalPengajuan.plusDays(1);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String tanggalPengajuanStr = tanggalPengajuan.format(formatter);
            String tanggalCairStr = tanggalCair.format(formatter);

            // Hitung total cair
            double totalCair = jumlahPinjaman * (1 + bunga); // Total cair = jumlah pinjaman + bunga
            String totalCairStr = String.format("%.2f", totalCair); // Format total cair menjadi string dengan 2 desimal

            // Hitung angsuran bulanan
            double angsuranBulanan = totalCair / tenorBulan; // Angsuran bulanan = total cair / tenor
            String angsuranBulananStr = String.format("%.2f", angsuranBulanan); // Format angsuran bulanan menjadi string dengan 2 desimal

            // Hitung sisa angsuran
            double sisaAngsuran = totalCair; // Sisa angsuran sama dengan total cair pada awalnya
            String sisaAngsuranStr = String.format("%.2f", sisaAngsuran); // Format sisa angsuran menjadi string dengan 2 desimal

            // Validasi input
            if (txtJumlah.getText().trim().isEmpty() || tenor.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua kolom harus diisi", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Update txtCicilan dengan format Rupiah
            txtCicilan.setText(String.format("Rp %,d", (int) Math.round(angsuranBulanan)));

            // Set status pengajuan
            String statusPengajuan = "Menunggu"; // Set status pengajuan
            String status = "belum lunas"; // Status pinjaman

            // Kirim data ke Kafka
            KirimData(String.valueOf(iduser),
                    String.valueOf(jumlahPinjaman),
                    String.valueOf(tenorBulan),
                    String.valueOf(bunga * 100),
                    angsuranBulananStr,
                    tanggalCairStr,
                    totalCairStr,
                    sisaAngsuranStr,
                    status,
                    statusPengajuan); // Pastikan jumlah parameter sesuai

            JOptionPane.showMessageDialog(this, "Data berhasil dikirim!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format jumlah atau tenor tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
    }//GEN-LAST:event_btnAjukanActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int jumlahPinjaman = Integer.parseInt(txtJumlah.getText());
            int tenor = 1;
            double bunga = 0.01; // Default bunga 1%

            String pilihanTenor = (String) CbTenor.getSelectedItem();
            switch (pilihanTenor) {
                case "1 Bulan":
                    tenor = 1;
                    break;
                case "3 Bulan":
                    tenor = 3;
                    break;
                case "6 Bulan":
                    tenor = 6;
                    break;
                case "12 Bulan":
                    tenor = 12;
                    break;
            }

            // Hitung cicilan dengan bunga 1%
            double totalCair = jumlahPinjaman * (1 + bunga);
            double cicilan = totalCair / tenor;
            int cicilanBulanan = (int) Math.round(cicilan);

            // Tampilkan hasil cicilan
            txtCicilan.setText(String.format("Rp %,d", cicilanBulanan));
        } catch (NumberFormatException e) {
            txtCicilan.setText("Input tidak valid!");
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        int loggedInUserId = 1;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengajuanPinjaman(loggedInUserId).setVisible(true);
            }
        });
    }

    private javax.swing.JComboBox<String> CbTenor;
    private javax.swing.JButton btnAjukan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTampil;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBunga;
    private javax.swing.JLabel txtCicilan;
    private javax.swing.JTextField txtJumlah;

}
