/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peminjamanonline_sister_kelompok4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.apache.kafka.clients.producer.KafkaProducer;

/**
 *
 * @author ACER
 */
public class PengajuanPinjaman extends javax.swing.JFrame {

    /**
     * Creates new form PengajuanPinjaman
     */
    public PengajuanPinjaman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAjukan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        CbTenor = new javax.swing.JComboBox<>();
        txtBunga = new javax.swing.JLabel();
        txtCicilan = new javax.swing.JLabel();
        btnTampil = new javax.swing.JButton();
        txtNasabah_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengajuan Pinjaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jumlah :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tenor :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Bunga :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Cicilan :");

        btnAjukan.setBackground(new java.awt.Color(102, 102, 255));
        btnAjukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAjukan.setForeground(new java.awt.Color(255, 255, 255));
        btnAjukan.setText("Ajukan");
        btnAjukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjukanActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(102, 102, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        CbTenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Bulan", "3 Bulan", "6 Bulan", "12 Bulan", " " }));
        CbTenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTenorActionPerformed(evt);
            }
        });

        txtBunga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBunga.setText("1 %");

        txtCicilan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCicilan.setText("Isi");

        btnTampil.setBackground(new java.awt.Color(102, 102, 255));
        btnTampil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampil.setForeground(new java.awt.Color(255, 255, 255));
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Id Nasabah :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTampil)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBunga))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCicilan))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKembali)
                                .addGap(68, 68, 68)
                                .addComponent(btnAjukan))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNasabah_id, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CbTenor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNasabah_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CbTenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBunga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCicilan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjukan)
                    .addComponent(btnKembali))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbTenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbTenorActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       
       this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnAjukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjukanActionPerformed
        try {
        // Mengambil input jumlah pinjaman dari txtJumlah
        double jumlah = Double.parseDouble(txtJumlah.getText());

        // Mendapatkan tenor dari combo box dan mengonversinya menjadi angka
        String tenorStr = (String) CbTenor.getSelectedItem();
        int tenor = Integer.parseInt(tenorStr.split(" ")[0]);

        // Bunga tetap 1% (0.01)
        double bunga = 0.01;

        // Menghitung cicilan per bulan
        double cicilan = (jumlah + (jumlah * bunga)) / tenor;

        // Menampilkan hasil cicilan pada txtCicilan
        txtCicilan.setText(String.format("%.2f", cicilan));

        // Mendapatkan nilai nasabah_id dari text field
        String nasabah_id = txtNasabah_id.getText();  // Mendapatkan nilai ID Nasabah dari txtNasabah_id

        if (nasabah_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Nasabah tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mengirim data ke database
        insertPinjaman(txtJumlah.getText(), tenorStr, String.format("%.2f", bunga * 100), String.format("%.2f", cicilan));

    } catch (NumberFormatException e) {
        // Menampilkan pesan error jika input jumlah tidak valid
        JOptionPane.showMessageDialog(this, "Masukkan jumlah pinjaman yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAjukanActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        try {
    // Mengambil input jumlah pinjaman dari txtJumlah
    double jumlah = Double.parseDouble(txtJumlah.getText());

    // Mendapatkan tenor dari combo box dan mengonversinya menjadi angka
    String tenorStr = (String) CbTenor.getSelectedItem();
    int tenor = Integer.parseInt(tenorStr.split(" ")[0]);

    // Bunga tetap 1% (0.01)
    double bunga = 0.01;

    // Memformat bunga menjadi persen (misalnya 0.01 menjadi 1.00)
    String bungaFormatted = String.format("%.2f", bunga * 100);  // Ini akan menyimpan 1.00 untuk 1%

    // Menghitung cicilan per bulan
    double cicilan = (jumlah + (jumlah * bunga)) / tenor;

    // Membulatkan cicilan menjadi bilangan bulat
    long cicilanBulat = Math.round(cicilan); // Membulatkan cicilan ke angka bulat

    // Menampilkan hasil cicilan pada txtCicilan
    txtCicilan.setText(String.valueOf(cicilanBulat)); // Menampilkan cicilan dalam bentuk bilangan bulat

    // Kirim data ke database
    insertPinjaman(txtJumlah.getText(), tenorStr, bungaFormatted, String.valueOf(cicilanBulat));  // Mengirimkan bunga yang sudah diformat

} catch (NumberFormatException e) {
    // Menampilkan pesan error jika input jumlah tidak valid
    JOptionPane.showMessageDialog(this, "Masukkan jumlah pinjaman yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
}


        
    }//GEN-LAST:event_btnTampilActionPerformed
    private void insertPinjaman(String jumlah, String tenor, String bunga, String cicilan) {
    Connection conn = null;
    PreparedStatement pst = null;

    try {
        // Koneksi ke database MySQL
        String url = "jdbc:mysql://localhost:3306/loan_app";  // Ganti dengan URL database Anda
        String user = "root";  // Ganti dengan username database Anda
        String password = "";  // Ganti dengan password database Anda
        conn = DriverManager.getConnection(url, user, password);

        // Mengonversi tenor menjadi angka (jumlah bulan)
        String tenorStr = (String) CbTenor.getSelectedItem();
        int tenorInt = Integer.parseInt(tenorStr.split(" ")[0]); // Mengambil angka dari string "1 Bulan" menjadi 1

        // SQL query untuk insert data
        String sql = "INSERT INTO pinjaman (nasabah_id, jumlah, tenor, suku_bunga, angsuran_bulanan) VALUES (?, ?, ?, ?, ?)";

        // Persiapkan statement
        pst = conn.prepareStatement(sql);
        String nasabah_id = null;

        // Menetapkan parameter dengan urutan yang benar
        pst.setString(1, nasabah_id);  // Menetapkan nasabah_id
        pst.setString(2, jumlah);  // Menetapkan jumlah
        pst.setInt(3, tenorInt);    // Menetapkan tenor sebagai angka
        pst.setString(4, bunga);    // Menetapkan bunga
        pst.setString(5, cicilan);  // Menetapkan cicilan

        // Eksekusi query
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diajukan", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        // Pindah ke halaman DashboardAdmin setelah pengajuan
        new DashboardAdmin().setVisible(true);
        this.setVisible(false);  // Menutup halaman pengajuan setelah berhasil

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (pst != null) pst.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menutup koneksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengajuanPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengajuanPinjaman().setVisible(true);
            }
        });
    }
    
    private void configureKafkaProducer() {
        var props = new java.util.Properties();
        props.put("bootstrap.servers", "localhost:9092");
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

        KafkaProducer<Object, Object> kafkaProducer = new KafkaProducer<>(props);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbTenor;
    private javax.swing.JButton btnAjukan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTampil;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBunga;
    private javax.swing.JLabel txtCicilan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNasabah_id;
    // End of variables declaration//GEN-END:variables
}
