
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peminjamanonline_sister_kelompok4;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

/**
 *
 * @author ACER
 */
public class RiwayatPinjaman extends javax.swing.JFrame {

    private Producer<String, String> kafkaProducer;
    private final int iduser;

    public RiwayatPinjaman(int iduser) {
        initComponents();
        configureKafkaProducer();
        this.iduser = iduser;
        tampilDataPinjaman();
    }

    /**
     * Creates new form RiwayatPinjaman
     */
    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPinjaman = new javax.swing.JLabel();
        txtJatuhTempo = new javax.swing.JLabel();
        txtTenor = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        txtTagihan = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtSisaTagihan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTanggalBayar = new javax.swing.JLabel();
        txtTanggalCair = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPelunasan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Riwayat Pinjaman");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jatuh Tempo :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tenor :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Status :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tagihan :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Pinjaman :");

        txtPinjaman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPinjaman.setText("-");

        txtJatuhTempo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtJatuhTempo.setText("-");

        txtTenor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTenor.setText("-");

        txtStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtStatus.setText("Pending");

        txtTagihan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTagihan.setText("-");

        btnBayar.setBackground(new java.awt.Color(102, 102, 255));
        btnBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Sisa Tagihan :");

        txtSisaTagihan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSisaTagihan.setText("-");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Tanggal Pencairan :");

        btnKembali.setBackground(new java.awt.Color(102, 102, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Tanggal Pembayaran :");

        txtTanggalBayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTanggalBayar.setText("-");

        txtTanggalCair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTanggalCair.setText("-");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Status pelunasan :");

        txtPelunasan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPelunasan.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJatuhTempo)
                    .addComponent(txtPinjaman)
                    .addComponent(txtTenor)
                    .addComponent(txtStatus)
                    .addComponent(txtTanggalCair)
                    .addComponent(txtTagihan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPelunasan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggalBayar))
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSisaTagihan)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPinjaman)
                    .addComponent(jLabel15)
                    .addComponent(txtTanggalBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJatuhTempo)
                    .addComponent(jLabel14)
                    .addComponent(txtSisaTagihan))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTanggalCair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel7)
                    .addComponent(txtTagihan)
                    .addComponent(txtPelunasan))
                .addGap(17, 17, 17)
                .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        int pinjaman_id = getSelectedPinjamanId(); // Method to get the selected loan ID

        if (pinjaman_id == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih pinjaman yang valid.");
            return;
        }

        Pembayaran pembayaran = new Pembayaran(iduser, pinjaman_id);
        pembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        int loggedInUserId = 1;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatPinjaman(loggedInUserId).setVisible(true);
            }
        });
    }

    private Date hitungJatuhTempo(Date tanggalPengajuan) {
        long millisPerDay = 24 * 60 * 60 * 1000L;
        return new Date(tanggalPengajuan.getTime() + (7 * millisPerDay));
    }

    private Date hitungTanggalPencairan(Date jatuhTempo) {
        long millisPerDay = 24 * 60 * 60 * 1000L;
        return new Date(jatuhTempo.getTime() + millisPerDay);
    }

    private String formatTanggal(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        return sdf.format(date);
    }

    private void configureKafkaProducer() {
        var props = new java.util.Properties();
        props.put("bootstrap.servers", "localhost:9092");
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

        kafkaProducer = new KafkaProducer<>(props);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtJatuhTempo;
    private javax.swing.JLabel txtPelunasan;
    private javax.swing.JLabel txtPinjaman;
    private javax.swing.JLabel txtSisaTagihan;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTagihan;
    private javax.swing.JLabel txtTanggalBayar;
    private javax.swing.JLabel txtTanggalCair;
    private javax.swing.JLabel txtTenor;
    // End of variables declaration//GEN-END:variables

    private void tampilDataPinjaman() {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            conn = DatabaseConnection.getConnection();

            // Updated SQL query to match the new table and column structure
            String query = "SELECT p.jumlah AS jumlah_pengajuan, t.jatuh_tempo, p.tanggal_cair, "
                    + "p.tenor, p.angsuran_bulanan, pp.status AS status_pengajuan, "
                    + "p.sisa_tagihan, p.status, t.jumlah_bayar, t.tanggal_pembayaran "
                    + "FROM pengajuan_pinjaman pp "
                    + "LEFT JOIN pinjaman p ON pp.pinjaman_id = p.pinjaman_id "
                    + "LEFT JOIN tagihan t ON p.pinjaman_id = t.pinjaman_id "
                    + "WHERE pp.iduser = ?";

            ps = conn.prepareStatement(query);
            ps.setInt(1, iduser); // Set parameter ID user with type int
            rs = ps.executeQuery();

            if (rs.next()) {
                // Data found
                txtPinjaman.setText(rs.getString("jumlah_pengajuan") != null ? rs.getString("jumlah_pengajuan") : "-");
                txtJatuhTempo.setText(rs.getString("jatuh_tempo") != null ? rs.getString("jatuh_tempo") : "-");
                txtTanggalCair.setText(rs.getString("tanggal_cair") != null ? rs.getString("tanggal_cair") : "-");
                txtTenor.setText(rs.getString("tenor") != null ? rs.getString("tenor") : "-");
                txtStatus.setText(rs.getString("status_pengajuan") != null ? rs.getString("status_pengajuan") : "-");
                txtTagihan.setText(rs.getString("jumlah_bayar") != null ? rs.getString("jumlah_bayar") : "-");
                txtSisaTagihan.setText(rs.getString("sisa_tagihan") != null ? rs.getString("sisa_tagihan") : "-");
                txtTanggalBayar.setText(rs.getString("tanggal_pembayaran") != null ? rs.getString("tanggal_pembayaran") : "-");
                txtPelunasan.setText(rs.getString("status") != null ? rs.getString("status") : "-");
            } else {
                // Data not found
                txtPinjaman.setText("-");
                txtJatuhTempo.setText("-");
                txtTanggalCair.setText("-");
                txtTenor.setText("-");
                txtStatus.setText("Pending");
                txtTagihan.setText("-");
                txtSisaTagihan.setText("-");
                txtTanggalBayar.setText("-");
                txtPelunasan.setText("-");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private int getSelectedPinjamanId() {
         return 1;
    }
}